'Example User Registration System - Diagram

@startuml

class User {
    -name: String
    -lastName: String
    -email: String
    -phone: int
    -address: String
    -age: int

    +register(): void
    +updateProfile(): void
    +getFullName(): String
}

class Location {
    -country: String
    -city: String
    -department: String

    +getFullLocation(): String
}

class Job {
    -name: String
    -profession: String
    -admissionDate: Date
    -typeContract: String

    +getJobInfo(): String
}

class Study {
    -name: String
    -admissionDate: Date
    -address: String

    +getStudyInfo(): String
}

User --> Location : lives in
User --> "*" Job : has
User --> "*" Study : studied

@enduml